server:
  port: 8080

spring:
  application:
    # 应用名称
    name: xiaofangwaimai
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  redis:
    host: 101.35.87.146
    port: 6379
    password: '031214'
    database: 0


mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      # 逻辑删除
#      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 删除掉为 1
#      logic-not-delete-value: 0 # 没有删除为 0


reggie:
#  path: F:\xiaofangwaimai\src\main\java\com\yefeng\images\ # 台式路径
  path: E:\xiaofangwaimai\src\main\java\com\yefeng\images\ # 笔记本路径